Repository boostcampwm-2021/WEB08-AgileStorming, pull requests merged in 2021-11, with the labels that each got.

#23 다함께 FE, BE 환경설정
  .prettierignore
  .prettierrc
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/App/index.tsx
  client/src/components/atoms/.gitkeep
  client/src/components/atoms/Button/index.tsx
  client/src/components/molecules/.gitkeep
  client/src/components/organisms/.gitkeep
  client/src/components/templates/.gitkeep
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/Calendar/index.tsx
  client/src/pages/Chart/index.tsx
  client/src/pages/Kanban/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/pages/Project/index.tsx
  client/src/pages/index.ts
  client/src/recoil/user/index.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
  client/src/styles/global.ts
  client/src/styles/index.ts
  client/src/utils/api.js
  client/tsconfig.json
  server/.gitignore
  server/README.md
  server/ormconfig.json
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/src/controller/UserController.ts
  server/src/index.ts
  server/src/routes.ts
  server/src/routes/user.ts
  server/src/services/UserService.ts
  server/tsconfig.json
Labels: FE, BE, 환경설정, DB

#25 Feature/login page#15
  client/src/components/.gitkeep
  client/src/components/atoms/.gitkeep
  client/src/components/atoms/BoxButton/index.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Title/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/organisms/.gitkeep
  client/src/components/organisms/LoginWrapper/index.tsx
  client/src/components/organisms/LoginWrapper/style.ts
  client/src/components/organisms/index.tsx
  client/src/components/templates/.gitkeep
  client/src/components/templates/Login/index.tsx
  client/src/components/templates/Login/style.ts
  client/src/img/img.d.ts
  client/src/img/index.ts
  client/src/img/logo.png
  client/src/pages/Login/index.tsx
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
Labels: FE

#27 로그인 페이지 리뷰 반영
  client/src/components/atoms/BoxButton/index.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/molecules/.gitkeep
  client/src/components/organisms/LoginWrapper/index.tsx
  client/src/hooks/.gitkeep
Labels: FE, refactor

#29 마우스로 마인드맵 이동 #2
  client/src/components/atoms/Background/index.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/utils/helpers.ts
Labels: FE

#30 Feature/login api#3
  server/package-lock.json
  server/package.json
  server/src/entity/User.ts
  server/src/index.ts
  server/src/routes.ts
  server/src/routes/auth.ts
  server/src/services/UserService.ts
  server/src/services/auth.ts
  server/src/services/user.ts
  server/src/utils/index.ts
Labels: BE

#31 새 프로젝트 생성
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/IconImg/index.tsx
  client/src/components/atoms/ModalBox/index.tsx
  client/src/components/atoms/ModalOverlay/index.tsx
  client/src/components/atoms/ShareButton/index.tsx
  client/src/components/atoms/SmallText/index.tsx
  client/src/components/atoms/Toast/index.tsx
  client/src/components/atoms/TransparentButton/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/IconButton/index.tsx
  client/src/components/molecules/TextButton/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/NewProjectCard/index.tsx
  client/src/components/organisms/ProjectCard/index.tsx
  client/src/components/organisms/TextInputModal/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/NewProjectModalWrapper/index.tsx
  client/src/components/templates/Project/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/components/templates/index.tsx
  client/src/hooks/toast/index.ts
  client/src/img/index.ts
  client/src/img/plus.svg
  client/src/pages/Project/index.tsx
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
Labels: FE

#33 dfs + css flex 를 이용해 정렬된 tree 형성
  client/src/components/atoms/Background/index.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/molecules/MindmapTree/index.tsx
  client/src/components/molecules/index.tsx
  client/src/hooks/useSocketSetup/index.ts
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/mindMap/index.ts
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
  client/src/utils/api.ts
Labels: FE

#34 첫 화면에 프로젝트 노드 생성 #6
  client/src/components/atoms/Background/index.tsx
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/molecules/MindmapTree/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/mindMap/index.ts
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
  client/src/utils/helpers.ts
Labels: FE

#39 Feature/register modal#18
  client/src/App/index.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/organisms/LoginWrapper/index.tsx
  client/src/components/organisms/RegisterModal/index.tsx
  client/src/components/templates/GlobalModal/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/hooks/useModal/index.ts
  client/src/hooks/useToast/index.ts
  client/src/pages/Project/index.tsx
  client/src/recoil/modal/index.ts
  client/src/utils/api.ts
Labels: FE

#42 헤더 바 구현 & 노드 이동 구현 #10 #20
  client/src/App/index.tsx
  client/src/components/atoms/Node/index.tsx
  client/src/components/atoms/svgCurve/index.tsx
  client/src/components/molecules/Header/index.tsx
  client/src/components/molecules/MindmapTree/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/LoginWrapper/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/Mindmap/index.tsx
  client/src/components/templates/index.tsx
  client/src/hooks/useSocketEmit/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/img/back.svg
  client/src/img/index.ts
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/mindMap/index.ts
  client/src/utils/helpers.ts
Labels: FE

#43 다중 토스트 기능
  client/src/components/atoms/Toast/index.tsx
  client/src/hooks/useToast/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/recoil/toast/index.ts
Labels: bug, FE

#46 마인드맵 로직 개선, useEvent, useDragEvent, useThrottle 커스텀 훅 정의 #10 #20
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/Header/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/hooks/useDragEvent/index.ts
  client/src/hooks/useEvents/index.ts
  client/src/hooks/useSocketEmit/index.ts
  client/src/hooks/useThrottle/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/utils/helpers.ts
Labels: FE

#55 Feature/auth middleware#5
  server/src/config/error-message.ts
  server/src/middlewares/auth.ts
  server/src/middlewares/user.ts
  server/src/routes/auth.ts
  server/src/routes/project.ts
  server/src/services/auth.ts
Labels: BE

#60 노드 추가 버튼 생성, 마인드맵 선 그리기 #12
  client/src/components/atoms/Background/index.tsx
  client/src/components/atoms/BoxButton/index.tsx
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/molecules/MindmapTree/index.tsx
  client/src/components/molecules/Path/index.tsx
  client/src/components/molecules/PrimaryButton/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/MindmapTemplate/index.tsx
  client/src/components/templates/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/mindmap/index.ts
  client/src/utils/helpers.ts
Labels: FE

#69 ♻️ 리뷰 반영, Tree 작업 변경사항 병합
  client/src/App/index.tsx
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/index.tsx
  client/src/hooks/useDragEvent/index.ts
  client/src/hooks/useThrottle/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/utils/helpers.ts
Labels: FE

#70 노드 상세정보창 UI 및 다수의 공용 컴포넌트
  client/src/components/atoms/BoxButton/index.tsx
  client/src/components/atoms/BoxButton/style.ts
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Input/style.ts
  client/src/components/atoms/Title/index.tsx
  client/src/components/atoms/Title/style.ts
  client/src/components/molecules/Label/index.tsx
  client/src/components/molecules/Label/style.ts
  client/src/components/molecules/PopupItemLayout/index.tsx
  client/src/components/molecules/PopupLayout/index.tsx
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/molecules/PrimaryButton/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/LoginWrapper/index.tsx
  client/src/components/organisms/LoginWrapper/style.ts
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/RegisterModal/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/hooks/useToast/index.ts
  client/src/img/closeIcon.svg
  client/src/img/filterIcon.svg
  client/src/img/index.ts
  client/src/pages/Kanban/index.tsx
  client/src/recoil/node/index.ts
  client/src/recoil/user/index.ts
  client/src/styles/common.ts
Labels: FE

#72 백엔드 소켓, 레디스 설정
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/components/templates/ProjectCardContainer/socket.ts
  server/.dockerignore
  server/Dockerfile
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/redis.conf
  server/src/database/entities/Mindmap.ts
  server/src/database/entities/Project.ts
  server/src/database/entities/Task.ts
  server/src/index.ts
  server/src/services/mindmap.ts
  server/src/services/project.ts
  server/src/utils/eventConverter.ts
  server/src/utils/index.ts
  server/src/utils/redis.ts
  server/src/utils/socket.ts
Labels: BE

#74 Feature/dropdown#71
  client/src/components/molecules/Dropdown/index.tsx
  client/src/components/molecules/Dropdown/style.ts
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/recoil/meta-data/index.ts
  client/src/recoil/node/index.ts
  client/src/styles/global.ts
Labels: FE

#75 노드 상세 정보 컴포넌트 입력값 제어
  client/src/components/atoms/Input/index.tsx
  client/src/components/molecules/Label/style.ts
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/recoil/node/index.ts
  client/src/utils/form.ts
  server/docker-compose.yml
Labels: FE

#77 유저 접속 상태 표시
  client/src/components/templates/ProjectCardContainer/socket.ts
  server/src/routes/project.ts
  server/src/services/project.ts
  server/src/utils/event-converter.ts
  server/src/utils/socket.ts
Labels: BE

#78 임시 노드에 내용 입력 시 실제 노드 생성 #17
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/Tree/style.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/style.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/mindmap/index.ts
  client/src/recoil/node/index.ts
  client/src/utils/helpers.ts
Labels: FE

#79 socket 관련 커스텀 훅 정의 #51
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/global.d.ts
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useSocketDisconnect/index.ts
  client/src/hooks/useSocketEmit/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/hooks/useUserReceiver/index.ts
  client/src/pages/Mindmap/index.tsx
  client/src/pages/Project/index.tsx
  client/src/recoil/history/index.ts
  client/src/recoil/socket/index.ts
  server/docker-compose.yml
  server/src/utils/socket.ts
Labels: FE

#80 ♻️ emitter 형식 리팩토링, IData 타입 재정의
  client/src/components/organisms/Mindmap/index.tsx
  client/src/hooks/useDragEvent/index.ts
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/recoil/history/index.ts
  client/src/recoil/mindmap/index.ts
Labels: FE

#82 좌 우 사이드바 병합 및 오류 해결, recoil node 리팩토링
  client/src/App/index.tsx
  client/src/components/molecules/Profile/index.tsx
  client/src/components/molecules/Spinner/index.css
  client/src/components/molecules/Spinner/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/hooks/useHistoryController/index.ts
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/history/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/recoil/node/index.ts
  server/src/utils/event-converter.ts
Labels: FE

#97 라벨, 스프린트 모델 추가
  server/src/database/entities/Label.ts
  server/src/database/entities/Project.ts
  server/src/database/entities/Sprint.ts
  server/src/routes/project.ts
  server/src/services/project.ts
Labels: BE

#99 🐛 도커 레디스 이슈, mysql 한글 이슈 해결
  docker-compose.yml
Labels: bug, BE

#101 히스토리 리스트는 가로로 나열되어 있고, 마우스를 눌러 스크롤 가능하다. #64
  client/src/components/atoms/Background/index.tsx
  client/src/components/atoms/DragTarget/index.tsx
  client/src/components/atoms/UserIcon/index.tsx
  client/src/components/atoms/UserIcon/style.ts
  client/src/components/atoms/index.tsx
  client/src/components/molecules/HistoryLog/index.tsx
  client/src/components/molecules/HistoryLog/style.tsx
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/HistoryWindow/style.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/molecules/Profile/index.tsx
  client/src/components/molecules/Profile/style.tsx
  client/src/components/organisms/HistoryBackground/index.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/components/organisms/HistoryBar/style.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/hooks/useDragBackground/functions.tsx
  client/src/hooks/useDragBackground/index.tsx
  client/src/pages/Mindmap/index.tsx
  client/src/styles/common.ts
  client/src/utils/helpers.ts
Labels: FE

#106 Feature/node position
  client/src/components/molecules/HistoryLog/index.tsx
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/hooks/useHistoryController/index.ts
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/recoil/history/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/types/event.ts
  client/src/types/history.ts
  client/src/types/mindmap.ts
  client/src/utils/helpers.ts
Labels: FE

#109 History API
  .vscode/settings.json
  server/package-lock.json
  server/package.json
  server/src/routes/history.ts
  server/src/routes/index.ts
  server/src/utils/redis.ts
Labels: BE

#111 mindmap 더미 데이터 삭제 후 DB 데이터 연동
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/templates/MindmapTemplate/index.tsx
  client/src/hooks/useSocketSetup/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/types/event.ts
  client/src/utils/api.ts
  server/src/database/entities/Mindmap.ts
  server/src/routes/project.ts
  server/src/services/mindmap.ts
  server/src/services/project.ts
  server/src/utils/event-type.ts
Labels: FE, BE

#112 스프린트, 라벨 추가 기능
  client/src/App/index.tsx
  client/src/components/atoms/ColorIcon/index.tsx
  client/src/components/atoms/ColorIcon/style.ts
  client/src/components/atoms/ModalOverlay/index.tsx
  client/src/components/atoms/SmallText/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/PopupItemLayout/index.tsx
  client/src/components/molecules/PopupLayout/index.tsx
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/NewProjectCard/index.tsx
  client/src/components/organisms/NewProjectCard/style.ts
  client/src/components/organisms/NewSprintModal/index.tsx
  client/src/components/organisms/NewSprintModal/style.ts
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/RegisterModal/index.tsx
  client/src/components/organisms/TextInputModal/index.tsx
  client/src/components/organisms/UserList/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/GlobalModal/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/components/templates/NewProjectModalWrapper/index.tsx
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useModal/index.ts
  client/src/hooks/useProject/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/hooks/useUserReceiver/index.ts
  client/src/recoil/history/index.ts
  client/src/recoil/modal/index.ts
  client/src/recoil/project/index.ts
  client/src/recoil/user-list/index.ts
  client/src/types/event.ts
  client/src/types/label.ts
  client/src/types/project.ts
  client/src/types/sprint.ts
  client/src/utils/api.ts
  client/src/utils/form.ts
  client/src/utils/parser.ts
  server/src/services/label.ts
  server/src/services/sprint.ts
  server/src/utils/event-converter.ts
  server/src/utils/socket.ts
Labels: FE, BE

#113 스크럼 반영: 프로젝트 정보 array에서 map으로 교체
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/UserList/index.tsx
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useProject/index.ts
  client/src/hooks/useUserReceiver/index.ts
  client/src/recoil/project/index.ts
Labels: FE

#115 프로젝트 칸반보드 페이지 UI, 작업상태 변경
  client/src/components/atoms/SmallText/index.tsx
  client/src/components/atoms/Wrapper/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/LabelIcon/index.tsx
  client/src/components/molecules/TaskInfo/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/TaskCard/index.tsx
  client/src/components/organisms/TaskCard/style.ts
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/TaskCardContainer/index.tsx
  client/src/components/templates/index.tsx
  client/src/pages/Kanban/index.tsx
  client/src/recoil/mindmap/index.ts
  client/src/styles/common.ts
  client/src/types/event.ts
  server/src/database/entities/Task.ts
  server/src/utils/event-converter.ts
  server/src/utils/event-type.ts
Labels: FE, BE

#116 Feature/update node detail
  client/src/components/atoms/ModalOverlay/index.tsx
  client/src/components/atoms/Toast/index.tsx
  client/src/components/molecules/Dropdown/index.tsx
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/TaskCard/index.tsx
  client/src/components/templates/TaskCardContainer/index.tsx
  client/src/hooks/useProject/index.ts
  client/src/types/event.ts
  client/src/types/project.ts
  client/src/utils/api.ts
  server/src/database/entities/Mindmap.ts
  server/src/database/entities/Task.ts
  server/src/routes/project.ts
  server/src/services/project.ts
  server/src/services/task.ts
  server/src/utils/event-type.ts
Labels: FE, BE

#117 Feature/#51
  client/src/components/organisms/Mindmap/index.tsx
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useProject/index.ts
  client/src/types/event.ts
  client/src/types/project.ts
  client/src/utils/helpers.ts
  server/src/database/entities/Mindmap.ts
  server/src/database/entities/Project.ts
  server/src/services/project.ts
  server/src/services/task.ts
  server/src/utils/event-converter.ts
  server/src/utils/event-type.ts
Labels: FE, BE

#119 마인드맵 필터링, 스프린트,라벨 삭제
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/organisms/ConfirmModal/index.tsx
  client/src/components/organisms/ConfirmModal/style.ts
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/style.ts
  client/src/components/templates/GlobalModal/index.tsx
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/recoil/modal/index.ts
  client/src/recoil/project/index.ts
  server/src/utils/event-converter.ts
Labels: FE

#120 마인드 맵 히스토리 반영 기능 #56
  client/src/components/molecules/HistoryLog/index.tsx
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/hooks/useHistoryController/index.ts
  client/src/pages/History/index.tsx
  client/src/recoil/history/index.ts
  client/src/utils/helpers.ts
  client/src/utils/historyHandler.ts
Labels: bug, FE

#122 인증 관리 커스텀훅
  .vscode/settings.json
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/RegisterModal/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/hooks/useAuthentication/index.ts
  client/src/hooks/useToast/index.ts
  client/src/pages/Project/index.tsx
  client/src/recoil/user/index.ts
  client/src/utils/api.ts
  server/src/routes/auth.ts
  server/src/services/auth.ts
Labels: FE, BE

#123 필터링, Task 변경 이력 UI 반영, 노드 드래그 영역 개선
  client/src/components/atoms/Node/index.tsx
  client/src/components/atoms/PriorityIcon/index.tsx
  client/src/components/atoms/UserIcon/style.ts
  client/src/components/atoms/index.tsx
  client/src/components/molecules/TempNode/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/Tree/style.tsx
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/Mindmap/index.tsx
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/templates/MindmapTemplate/index.tsx
  client/src/hooks/useDragNode/index.ts
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/img/index.ts
  client/src/img/siren-green.svg
  client/src/img/siren-orange.svg
  client/src/img/siren-red.svg
  client/src/recoil/meta-data/index.ts
  client/src/recoil/mindmap/index.ts
  client/src/types/event.ts
  server/src/utils/event-type.ts
Labels: FE

#125 라벨 추가 기능
  client/src/components/molecules/LabelIcon/index.tsx
  client/src/components/molecules/LabelIcon/style.ts
  client/src/components/molecules/index.tsx
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/LabelList/index.tsx
  client/src/components/organisms/LabelList/style.ts
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/index.tsx
  client/src/types/event.ts
  server/src/database/entities/Task.ts
  server/src/services/task.ts
  server/src/utils/event-type.ts
Labels: FE, BE

#126 히스토리 리스트에서 특정 원을 클릭하면 현재 보고 있는 시점에서 클릭한 원까지의 변화 과정을 보여주며 이동한다. #66 / #124
  client/src/components/molecules/HistoryLog/index.tsx
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/HistoryWindow/style.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/hooks/useHistoryController/index.ts
  client/src/hooks/useLog/index.tsx
  client/src/recoil/history/index.ts
  client/src/utils/historyHandler.ts
Labels: FE

#127 백로그 페이지
  client/package.json
  client/src/App/index.tsx
  client/src/components/atoms/ColorIcon/index.tsx
  client/src/components/atoms/ColorIcon/style.ts
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/organisms/BacklogTable/StoryBacklog.tsx
  client/src/components/organisms/BacklogTable/TaskBacklog.tsx
  client/src/components/organisms/BacklogTable/index.tsx
  client/src/components/organisms/BacklogTable/style.ts
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/TaskCard/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/components/templates/index.tsx
  client/src/hooks/useLinkClick/index.tsx
  client/src/img/index.ts
  client/src/img/logo-big-primary.png
  client/src/img/logo-big.png
  client/src/img/logo-move-primary.gif
  client/src/img/logo-move-white.gif
  client/src/pages/Backlog/index.tsx
  client/src/pages/index.ts
  client/src/recoil/project/index.ts
  client/src/types/page.ts
  server/package.json
Labels: FE

#128 히스토리 playController, 히스토리 더 가져오기, 변경 속도 조절 기능 #68 / #110 / #67
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/HistoryWindow/style.tsx
  client/src/components/molecules/PlayController/index.tsx
  client/src/components/molecules/PlayController/style.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/components/organisms/HistoryBar/style.tsx
  client/src/components/organisms/HistoryHeader/index.tsx
  client/src/components/organisms/HistoryHeader/style.tsx
  client/src/components/organisms/index.tsx
  client/src/hooks/useHistoryController/index.ts
  client/src/hooks/useLinkClick/index.tsx
  client/src/hooks/useNewHistoryData/index.tsx
  client/src/img/index.ts
  client/src/img/pauseBtn.svg
  client/src/img/primaryPlusCircle.svg
  client/src/pages/History/index.tsx
  client/src/recoil/history/index.ts
  client/src/types/history.ts
  client/src/utils/parser.ts
Labels: FE

#131 도커, nginx https 세팅
  docker-compose.yml
  nginx/default.conf
Labels: BE

#145 노드 삭제 시 히스토리에서 발생하는 버그를 해결
  client/src/components/molecules/Tree/index.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useLog/index.tsx
  client/src/utils/historyHandler.ts
Labels: bug

#148 스프린트, 라벨 태스크 삭제 시 발생하는 버그를 해결한다.
  client/src/components/molecules/Dropdown/index.tsx
  client/src/components/molecules/LabelIcon/index.tsx
  client/src/components/organisms/BacklogTable/TaskBacklog.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/TaskCard/index.tsx
Labels: bug, FE

#150 delete 버그 해결, 삭제 버튼 스타일 구현
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/Tree/style.tsx
  client/src/components/organisms/Mindmap/index.tsx
  client/src/hooks/useHistoryReceiver/index.ts
Labels: bug, FE

#151 https로 인한 cd 에러 해결
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/LabelList/style.ts
  docker-compose.yml
Labels: BE, devops

#159 project 삭제 시 steam에서 history 데이터도 삭제
  server/src/routes/project.ts
  server/src/utils/redis.ts
Labels: BE, DB

#160 mindmap과 history에 Delete시 SideEffect 반영
  client/src/components/atoms/Node/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/Tree/style.tsx
  client/src/components/organisms/MindmapTree/index.tsx
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useLog/index.tsx
  client/src/recoil/history/index.ts
  client/src/types/event.ts
  client/src/types/mindmap.ts
  client/src/utils/helpers.ts
  client/src/utils/historyHandler.ts
  server/src/database/entities/Mindmap.ts
  server/src/services/mindmap.ts
  server/src/services/project.ts
  server/src/utils/event-converter.ts
  server/src/utils/event-type.ts
Labels: bug

#163 번다운차트, 파이차트
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Title/index.tsx
  client/src/components/atoms/Title/style.ts
  client/src/components/organisms/BurnDownChart/index.tsx
  client/src/components/organisms/TaskRatioChart/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/ChartContainer/ChartHeader.tsx
  client/src/components/templates/ChartContainer/index.tsx
  client/src/components/templates/ChartContainer/style.ts
  client/src/components/templates/index.tsx
  client/src/pages/Chart/index.tsx
  client/src/recoil/chart/index.ts
  client/src/recoil/project/index.ts
Labels: FE

#164 캘린더 페이지
  client/src/components/atoms/IconImg/index.tsx
  client/src/components/molecules/IconButton/index.tsx
  client/src/components/organisms/BacklogTable/style.ts
  client/src/components/organisms/ScheduleCalendar/Calendar.tsx
  client/src/components/organisms/ScheduleCalendar/LayerScheduleDay.tsx
  client/src/components/organisms/ScheduleCalendar/LayerScheduleMonth.tsx
  client/src/components/organisms/ScheduleCalendar/LayerSprintDay.tsx
  client/src/components/organisms/ScheduleCalendar/LayerSprintMonth.tsx
  client/src/components/organisms/ScheduleCalendar/LayerTaskDetailDay.tsx
  client/src/components/organisms/ScheduleCalendar/LayerTaskDetailMonth.tsx
  client/src/components/organisms/ScheduleCalendar/MonthSelector.tsx
  client/src/components/organisms/ScheduleCalendar/index.tsx
  client/src/components/organisms/ScheduleCalendar/style.ts
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/style.ts
  client/src/img/arrow-left.svg
  client/src/img/arrow-right.svg
  client/src/img/index.ts
  client/src/pages/Backlog/index.tsx
  client/src/pages/Calendar/index.tsx
  client/src/utils/date.ts
Labels: FE

#167 Task 완료도 및 우선순위 차트 구현 & 사용자 노드 포커싱 소켓 이벤트 구현
  client/src/components/atoms/NodeTag/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/Tree/style.tsx
  client/src/components/molecules/UserFocusBox/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/DoneTaskChart/index.tsx
  client/src/components/organisms/PriorityChart/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/ChartContainer/ChartHeader.tsx
  client/src/components/templates/ChartContainer/index.tsx
  client/src/hooks/useHistoryEmitter/index.ts
  client/src/hooks/useSocketDisconnect/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/pages/Mindmap/index.tsx
  client/src/recoil/chart/index.ts
  client/src/recoil/project/index.ts
  server/src/utils/socket.ts
Labels: FE, BE

#170 각종 text overflow ui 처리, 번다운 차트 수정
  client/src/components/atoms/Title/index.tsx
  client/src/components/atoms/Title/style.ts
  client/src/components/molecules/Profile/index.tsx
  client/src/components/organisms/BurnDownChart/index.tsx
  client/src/components/organisms/TaskCard/index.tsx
  client/src/components/organisms/TaskCard/style.ts
  client/src/components/organisms/UserInProgressList/index.tsx
  client/src/components/organisms/UserInProgressList/style.ts
  client/src/components/organisms/UserList/index.tsx
  server/src/services/project.ts
Labels: UI

#171 Feature/#168#169
  client/src/components/atoms/UserIcon/index.tsx
  client/src/components/atoms/UserIcon/style.ts
  client/src/components/organisms/BacklogTable/style.ts
  client/src/components/organisms/ConfirmModal/index.tsx
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/NewSprintModal/index.tsx
  client/src/components/organisms/RegisterModal/index.tsx
  client/src/components/organisms/ScheduleCalendar/LayerScheduleDay.tsx
  client/src/components/organisms/ScheduleCalendar/style.ts
  client/src/components/organisms/TextInputModal/index.tsx
  client/src/components/templates/CommonLayout/FilterButton.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/TaskCardContainer/index.tsx
  client/src/hooks/useKeys/index.ts
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
Labels: FE

#172 달력, 백로그 UI 개선
  client/src/components/molecules/LabelIcon/style.ts
  client/src/components/organisms/BacklogTable/style.ts
  client/src/components/organisms/FilterPopup/style.ts
  client/src/components/organisms/ScheduleCalendar/LayerScheduleDay.tsx
  client/src/components/organisms/ScheduleCalendar/style.ts
Labels: FE

#176 1~10일 캘린더 태스크 안그려지는 버그
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/ScheduleCalendar/LayerScheduleMonth.tsx
Labels: bug

#178 마우스로 드래그 기능 리팩토링
  client/src/components/atoms/Background/index.tsx
  client/src/components/atoms/DragTarget/index.tsx
  client/src/components/atoms/index.tsx
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/HistoryWindow/style.tsx
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/organisms/HistoryBackground/index.tsx
  client/src/components/organisms/HistoryBar/index.tsx
  client/src/components/organisms/HistoryHeader/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/CommonLayout/style.ts
  client/src/hooks/useDragBackground/functions.tsx
  client/src/hooks/useDragBackground/index.tsx
  client/src/pages/Mindmap/index.tsx
Labels: bug, FE

#179 히스토리 포커싱
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/Tree/index.tsx
Labels: FE

#180 배경 드래그로 스크롤 범위 확장
  client/src/hooks/useDragBackground/index.tsx
Labels: bug

#181 pm2 설치 + ci 테스트 환경 구축
  .husky/pre-commit
  client/Dockerfile
  server/Dockerfile
  server/package-lock.json
  server/package.json
Labels: 환경설정, devops

#182 선택된 히스토리 중앙 위치 버그 수정
  client/src/components/molecules/HistoryWindow/index.tsx
  client/src/components/molecules/HistoryWindow/style.tsx
  client/src/hooks/useDragBackground/index.tsx
  client/src/hooks/useHistoryController/index.ts
Labels: bug

#196 노드 필터링 테스트 + 도커 redis 볼륨 이슈 해결
  client/src/components/organisms/FilterPopup/index.test.tsx
  client/src/recoil/project/index.test.ts
  client/src/setupTests.ts
  client/src/styles/global.ts
  docker-compose.yml
Labels: FE, devops

#197 artillery 부하테스트
  README.md
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/tests/artillery/api-stress.yml
  server/tests/artillery/socket-stress.yml
  server/tests/artillery/test.sh
Labels: BE, test
