Repository boostcampwm-2021/WEB08-AgileStorming, pull requests merged in 2021-12, with the labels that each got.

#201 캘린더 컴포넌트 분리 + 상세정보장 애니메이션 추가 및 엔터키 지원
  client/src/components/atoms/Buttons/BoxButton/index.tsx
  client/src/components/atoms/Buttons/BoxButton/style.ts
  client/src/components/atoms/Buttons/TransparentButton/index.tsx
  client/src/components/atoms/Buttons/TransparentButton/style.ts
  client/src/components/atoms/CalendarDays/LayerDay/index.tsx
  client/src/components/atoms/CalendarDays/LayerScheduleDay/index.tsx
  client/src/components/atoms/CalendarDays/LayerScheduleDay/style.ts
  client/src/components/atoms/CalendarDays/LayerSprintDay/index.tsx
  client/src/components/atoms/CalendarDays/LayerSprintDay/style.ts
  client/src/components/atoms/CalendarDays/LayerTaskDetailDay/index.tsx
  client/src/components/atoms/CalendarDays/LayerTaskDetailDay/style.ts
  client/src/components/atoms/Icons/ColorIcon/index.tsx
  client/src/components/atoms/Icons/LabelIcon/index.tsx
  client/src/components/atoms/Icons/LabelIcon/style.ts
  client/src/components/atoms/Icons/PriorityIcon/index.tsx
  client/src/components/atoms/Icons/PriorityIcon/style.ts
  client/src/components/atoms/Icons/UserIcon/index.tsx
  client/src/components/atoms/Icons/UserIcon/style.ts
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/ModalBox/index.tsx
  client/src/components/atoms/Texts/SmallText/index.tsx
  client/src/components/atoms/Texts/Title/index.tsx
  client/src/components/atoms/Texts/Title/style.ts
  client/src/components/atoms/index.tsx
  client/src/components/molecules/Calendars/Calendar/index.tsx
  client/src/components/molecules/Calendars/Calendar/style.ts
  client/src/components/molecules/Calendars/LayerScheduleCalendar/index.tsx
  client/src/components/molecules/Calendars/LayerSprintCalendar/index.tsx
  client/src/components/molecules/Calendars/LayerTaskDetailCalendar/index.tsx
  client/src/components/molecules/MonthSelector/index.tsx
  client/src/components/molecules/MonthSelector/style.ts
  client/src/components/molecules/PopupLayout/index.tsx
  client/src/components/molecules/PopupLayout/style.ts
  client/src/components/molecules/index.tsx
  client/src/components/organisms/BacklogTable/TaskBacklog.tsx
  client/src/components/organisms/FilterPopup/index.tsx
  client/src/components/organisms/LabelList/index.tsx
  client/src/components/organisms/Modals/ConfirmModal/index.tsx
  client/src/components/organisms/Modals/ConfirmModal/style.ts
  client/src/components/organisms/Modals/NewSprintModal/index.tsx
  client/src/components/organisms/Modals/NewSprintModal/style.ts
  client/src/components/organisms/Modals/RegisterModal/index.tsx
  client/src/components/organisms/Modals/TextInputModal/index.tsx
  client/src/components/organisms/NodeDetailWrapper/index.tsx
  client/src/components/organisms/ScheduleCalendar/index.tsx
  client/src/components/organisms/ScheduleCalendar/style.ts
  client/src/components/organisms/TaskCard/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/GlobalModal/index.tsx
  client/src/recoil/modal/index.ts
Labels: FE

#206 컴포넌트 폴더 구조 개선 작업
  .vscode/settings.json
  client/src/App/index.tsx
  client/src/components/atoms/Backgrounds/Background/index.tsx
  client/src/components/atoms/Backgrounds/Background/style.tsx
  client/src/components/atoms/Backgrounds/ModalOverlay/index.tsx
  client/src/components/atoms/Backgrounds/SpinnerBackground/index.css
  client/src/components/atoms/Backgrounds/SpinnerBackground/index.tsx
  client/src/components/atoms/Toast/index.tsx
  client/src/components/atoms/Toast/style.ts
  client/src/components/atoms/index.tsx
  client/src/components/molecules/Buttons/IconButton/index.tsx
  client/src/components/molecules/Buttons/TextButton/index.tsx
  client/src/components/molecules/Buttons/TextButton/style.ts
  client/src/components/molecules/Controllers/MonthController/index.tsx
  client/src/components/molecules/Controllers/MonthController/style.ts
  client/src/components/molecules/Controllers/PlayController/index.tsx
  client/src/components/molecules/Controllers/PlayController/style.tsx
  client/src/components/molecules/Layouts/LabelLayout/index.tsx
  client/src/components/molecules/Layouts/LabelLayout/style.ts
  client/src/components/molecules/Layouts/PopupItemLayout/index.tsx
  client/src/components/molecules/Layouts/PopupLayout/index.tsx
  client/src/components/molecules/Layouts/PopupLayout/style.ts
  client/src/components/molecules/MindmapBackground/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/Charts/BurnDownChart/index.tsx
  client/src/components/organisms/Charts/DoneTaskChart/index.tsx
  client/src/components/organisms/Charts/PriorityChart/index.tsx
  client/src/components/organisms/Charts/TaskRatioChart/index.tsx
  client/src/components/organisms/Popups/FilterPopup/index.test.tsx
  client/src/components/organisms/Popups/FilterPopup/index.tsx
  client/src/components/organisms/Popups/FilterPopup/style.ts
  client/src/components/organisms/Popups/NodeDetailPopup/index.tsx
  client/src/components/organisms/Popups/UserInProgressPopup/index.tsx
  client/src/components/organisms/Popups/UserInProgressPopup/style.ts
  client/src/components/organisms/Popups/UserListPopup/index.tsx
  client/src/components/organisms/ScheduleCalendar/index.tsx
  client/src/components/organisms/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/MindmapTemplate/index.tsx
  client/src/hooks/useToast/index.ts
Labels: bug, FE

#207 헤더 구현, 라우팅 처리, useHistoryReceiver test코드 작성, 버그 제거
  client/src/App/index.tsx
  client/src/components/atoms/Icons/PriorityIcon/style.ts
  client/src/components/molecules/Tree/index.tsx
  client/src/components/molecules/UserFocusBox/index.tsx
  client/src/components/organisms/Charts/DoneTaskChart/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Header/style.ts
  client/src/components/organisms/MindmapBtnWrapper/index.tsx
  client/src/components/organisms/Popups/UserInProgressPopup/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/Login/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/hooks/useAuthentication/index.ts
  client/src/hooks/useCustomHistory/index.ts
  client/src/hooks/useHistoryReceiver/index.test.tsx
  client/src/hooks/useHistoryReceiver/index.ts
  client/src/hooks/useLinkClick/index.tsx
  client/src/hooks/useNewHistoryData/index.tsx
  client/src/hooks/useProject/index.ts
  client/src/hooks/useProjectId/index.tsx
  client/src/hooks/useSocketDisconnect/index.ts
  client/src/hooks/useSocketSetup/index.ts
  client/src/recoil/project/index.ts
  client/src/styles/common.ts
  client/src/styles/emotion.d.ts
  client/src/utils/helpers.ts
  server/package.json
  server/src/utils/socket.ts
Labels: FE

#210 히스토리 로그 버그, 프로젝트 카드 삭제 버튼 이슈 #208, #209
  client/src/components/organisms/ProjectCard/index.tsx
  client/src/components/organisms/ProjectCard/style.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/hooks/useLog/index.tsx
Labels: bug, FE

#211 헤더 라우팅 오류 수정
  client/src/components/molecules/UserFocusBox/index.tsx
  client/src/components/organisms/HistoryBackground/index.tsx
  client/src/components/organisms/HistoryHeader/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/hooks/useLinkClick/index.tsx
  client/src/utils/helpers.ts
Labels: FE

#217 라벨 로그 이슈
  client/src/components/molecules/Dropdown/style.ts
  client/src/components/organisms/Popups/NodeDetailPopup/index.tsx
  client/src/components/templates/ProjectCardContainer/index.tsx
  client/src/hooks/useAuthentication/index.ts
Labels: bug

#220 CI/CD release 브랜치에만 적용하도록 변경 + 배포 후 버그 수정
  .github/workflows/CI-CD.yml
  client/src/components/molecules/BacklogRows/StoryBacklog/index.tsx
  client/src/components/molecules/BacklogRows/StoryBacklog/style.ts
  client/src/components/molecules/BacklogRows/TaskBacklog/index.tsx
  client/src/components/molecules/BacklogRows/TaskBacklog/style.ts
  client/src/components/molecules/Buttons/FilterButton/index.tsx
  client/src/components/molecules/index.tsx
  client/src/components/organisms/BacklogTable/index.tsx
  client/src/components/organisms/BacklogTable/style.ts
  client/src/components/organisms/Modals/RegisterModal/index.tsx
  client/src/components/templates/CommonLayout/index.tsx
  client/src/components/templates/Login/index.tsx
Labels: FE, BE

#222 캘린더 단위 테스트 추가
  client/fixtures/tasks.ts
  client/src/components/atoms/CalendarDays/LayerScheduleDay/index.test.tsx
  client/src/components/molecules/Calendars/Calendar/index.test.tsx
  client/src/utils/test.tsx
Labels: test
